alter table FIAS_HOUSE add column POSTALCODE varchar(6) ;
alter table FIAS_HOUSE add column IFNSFL varchar(4) ;
alter table FIAS_HOUSE add column TERRIFNSFL varchar(4) ;
alter table FIAS_HOUSE add column IFNSUL varchar(4) ;
alter table FIAS_HOUSE add column TERRIFNSUL varchar(4) ;
alter table FIAS_HOUSE add column OKATO varchar(11) ;
alter table FIAS_HOUSE add column OKTMO varchar(11) ;
alter table FIAS_HOUSE add column HOUSENUM varchar(20) ;
-- update FIAS_HOUSE set PARENT_ID = <default_value> where PARENT_ID is null ;
alter table FIAS_HOUSE alter column PARENT_ID set not null ;
